### ISSUE TITLE
Import discards all except last of same-name HTTP header fields

### ISSUE THREAD

**Issue by sebastian-nagel** [Florents-Tselai/warcio-sqlite#1]
If a WARC record includes multiple HTTP header fields of the same same (eg. [multiple "Set-Cookie" headers](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2)) only the last one is stored in database.

**Comment by Florents-Tselai** [comment]
Thanks @sebastian-nagel 

I should make the serialization smarter. 

I suppose I could wrap `[http.client.HTTPMessage](https://docs.python.org/3/library/http.client.html#httpmessage-objects)` and `[email.parser.Parser](https://docs.python.org/3/library/email.parser.html#email.parser.Parser)`

We'd still be in RFC 822/7230 territory.
